root: true
env:
    node: true
parser: '@typescript-eslint/parser'
parserOptions:
    sourceType: module
plugins:
    - '@typescript-eslint'
    - prettier
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:prettier/recommended
    - plugin:import/errors
    - plugin:import/warnings
    - plugin:import/typescript
rules:
    curly: error
    no-return-await: off
    prefer-arrow-callback: error
    prettier/prettier:
        - error
        - arrowParens: always
          semi: true
          singleQuote: true
          trailingComma: all
          endOfLine: auto
    require-await: off
    no-unused-vars: off
    '@typescript-eslint/no-unused-vars':
        - error
    import/order:
        - error
        - newlines-between: always